name: Deploy Feature Branches to Azure

on:
  push:
    branches:
      - feature/**

jobs:
  build_and_deploy_preview:
    runs-on: ubuntu-latest
    name: Build and Deploy Preview
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy Preview
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_SEA_0BCE09310 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/my-game-lib"
          api_location: ""
          output_location: "build"
        env:
          REACT_APP_FIREBASE_CONFIG: ${{ secrets.REACT_APP_FIREBASE_CONFIG}}
          REACT_APP_RAWG_API_KEY: ${{ secrets.REACT_APP_RAWG_API_KEY}}
